### ISSUE TITLE
DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()

### ISSUE THREAD

**Issue by DX37** [abbat/ydcmd#45]
При использовании новых версий Python (конкретно `3.10.1`) возникает следующая ошибка:
```
/usr/bin/ydcmd:272: DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()
  self.sock = ssl.wrap_socket(sock, keyfile = self.key_file, certfile = self.cert_file, **kwargs)
```

**Comment by abbat** [comment]
Проверьте пожалуйста сейчас.

**Comment by DX37** [comment]
Предупреждения больше нет. Благодарю!

**Comment by deadsandro** [comment]
При переезде сервера обнаружил.

```
Traceback (most recent call last):
  File "/usr/local/bin/ydcmd", line 2668, in <module>
    yd_ls_cmd(options, args)
  File "/usr/local/bin/ydcmd", line 1988, in yd_ls_cmd
    result = listvalues(yd_list(options, yd_remote_path(path)))
  File "/usr/local/bin/ydcmd", line 1105, in yd_list
    part = yd_query(options, method, url, args)
  File "/usr/local/bin/ydcmd", line 967, in yd_query
    return yd_query_retry(options, method, url, args, headers, target, data)
  File "/usr/local/bin/ydcmd", line 903, in yd_query_retry
    result = opener.open(request, timeout = options.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/bin/ydcmd", line 413, in https_open
    return self.do_open(self._get_connection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/local/bin/ydcmd", line 314, in request
    self._send_request(method, url, body, headers, **kwargs)
  File "/usr/lib/python2.7/httplib.py", line 1098, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1054, in endheaders
    self._send_output(message_body)
  File "/usr/local/bin/ydcmd", line 370, in _send_output
    self.send(msg)
  File "/usr/local/bin/ydcmd", line 382, in send
    self.connect()
  File "/usr/local/bin/ydcmd", line 274, in connect
    context.check_hostname = True
ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED
```
```
# python -V
Python 2.7.16

# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

# git log
commit 9b8e16631071688e2cda5dbbdc85c6d48ce42a01
Merge: 12f0e85 2279c19
```

На старом сервере последний коммит [35d704d6f7629bd9e519de483693639e8835e944](https://github.com/abbat/ydcmd/commit/35d704d6f7629bd9e519de483693639e8835e944) , там все работает.
Python 2.7.13, Debian 9.13
